[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "bark @ git+https://github.com/suno-ai/bark.git"
]
requires-python = ">=3.10"
license = {text = "MIT"}
